//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace OfficeExtractText.Properties {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("OfficeExtractText.Properties.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   厳密に型指定されたこのリソース クラスを使用して、すべての検索リソースに対し、
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Extract text from excel, word, powerpoint files and save as &lt;filename&gt;+&apos;.txt&apos; file in the specified output directory. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string APP_DESCRIPTION {
            get {
                return ResourceManager.GetString("APP_DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ERROR:  に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ERROR_PREFIX {
            get {
                return ResourceManager.GetString("ERROR_PREFIX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Extract excel files. 
        ///                   If -e, -w and -p options are not specified, 
        ///                   all office(excel, word, powerpoint) files are extracted. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string EXCEL_OPTION {
            get {
                return ResourceManager.GetString("EXCEL_OPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Extracting text is finished successfully. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string EXTRACTING_FINISHED_SUCCESSFULLY {
            get {
                return ResourceManager.GetString("EXTRACTING_FINISHED_SUCCESSFULLY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Extracting text is finished with error(s).
        ///Details:{0} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string EXTRACTING_FINISHED_WITH_ERROR_DETAILS_ARG0 {
            get {
                return ResourceManager.GetString("EXTRACTING_FINISHED_WITH_ERROR_DETAILS_ARG0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Extracting text is finished with warning(s). に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string EXTRACTING_FINISHED_WITH_WARNING {
            get {
                return ResourceManager.GetString("EXTRACTING_FINISHED_WITH_WARNING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Extracting text is started for the following path.
        ///Path:{0} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string EXTRACTING_STARTED_PATH_ARG0 {
            get {
                return ResourceManager.GetString("EXTRACTING_STARTED_PATH_ARG0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Extracting text. Path:{0} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string EXTRACTING_TEXT_PATH_ARG0 {
            get {
                return ResourceManager.GetString("EXTRACTING_TEXT_PATH_ARG0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   LOG:  に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string LOG_PREFIX {
            get {
                return ResourceManager.GetString("LOG_PREFIX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   No target office file in the specifined directory. Path:{0} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string NO_TARGET_FILE_IN_SPECIFIED_DIRECTORY_PATH_ARG0 {
            get {
                return ResourceManager.GetString("NO_TARGET_FILE_IN_SPECIFIED_DIRECTORY_PATH_ARG0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   No target office file found. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string NO_TARGET_FOUND {
            get {
                return ResourceManager.GetString("NO_TARGET_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Extract without log messages. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string NOLOG_OPTION {
            get {
                return ResourceManager.GetString("NOLOG_OPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Specified path is not an office file. Path:{0} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string NOT_TARGET_OFFICE_FILE_PATH_ARG0 {
            get {
                return ResourceManager.GetString("NOT_TARGET_OFFICE_FILE_PATH_ARG0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   &lt;output_directory&gt;(Required) Specify output directory of text files.  に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string OUTPUT_OPTION {
            get {
                return ResourceManager.GetString("OUTPUT_OPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Extract powerpoint files. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string POWERPOINT_OPTION {
            get {
                return ResourceManager.GetString("POWERPOINT_OPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Skip extracting text due to the following error. Path:{0}
        ///Details:{1} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SKIPPED_EXTRACTING_TEXT_PATH_ARG0_DETAILS_ARG1 {
            get {
                return ResourceManager.GetString("SKIPPED_EXTRACTING_TEXT_PATH_ARG0_DETAILS_ARG1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Speficied file path is not a target office file. Path:{0} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SPECIFIED_FILE_PATH_IS_NOT_TARGET_FILE_PATH_ARG0 {
            get {
                return ResourceManager.GetString("SPECIFIED_FILE_PATH_IS_NOT_TARGET_FILE_PATH_ARG0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Specified path is not existing or invalid. Path:{0} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SPECIFIED_PATH_IS_NOT_FILE_NOR_DIRECTORY_PATH_ARG0 {
            get {
                return ResourceManager.GetString("SPECIFIED_PATH_IS_NOT_FILE_NOR_DIRECTORY_PATH_ARG0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Stop extracting text because of an error. Path:{0}
        ///Details:{1} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string STOP_EXTRACTING_TEXT_PATH_ARG0_DETAILS_ARG1 {
            get {
                return ResourceManager.GetString("STOP_EXTRACTING_TEXT_PATH_ARG0_DETAILS_ARG1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Extract files in all sub directories. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SUBDIR_OPTION {
            get {
                return ResourceManager.GetString("SUBDIR_OPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Specify target file path or directory. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string TARGET_PATH_ARGUMENT {
            get {
                return ResourceManager.GetString("TARGET_PATH_ARGUMENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   WARNING:  に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string WARNING_PREFIX {
            get {
                return ResourceManager.GetString("WARNING_PREFIX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Extract word files. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string WORD_OPTION {
            get {
                return ResourceManager.GetString("WORD_OPTION", resourceCulture);
            }
        }
    }
}
